name: Deploy GitHub Pages

on:
    push:
        branches:
            - main

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: github-pages
    cancel-in-progress: true

jobs:
    build:
        name: Preparar frontend
        runs-on: ubuntu-latest

        steps:
            - name: Baixar repositório
              uses: actions/checkout@v7

            - name: Configurar GitHub Pages
              uses: actions/configure-pages@v6

            - name: Validar pasta pública
              shell: bash
              run: |
                  if [ ! -d "public" ]; then
                    echo "::error::A pasta public não existe."
                    exit 1
                  fi

                  if [ ! -f "public/index.html" ]; then
                    echo "::error::O arquivo public/index.html não existe."
                    exit 1
                  fi

                  touch public/.nojekyll

            - name: Criar artefato do GitHub Pages
              uses: actions/upload-pages-artifact@v5
              with:
                  path: ./public

    deploy:
        name: Publicar frontend
        needs: build
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Publicar no GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v5
